### PR TITLE
(hopefully) fix broken links, adds vmware fusion, cleans up the windows section

### PR DESCRIPTION
**Pull request by pumpkintheproot**
hihi, while browsing your download website, noticed a few links which would redirect to missing files (mostly redirecting to .isos that didnt exist) so i decided to fix them up myself, went through every download link (except betas, because thats about 100+ links to go through), also adds vmware fusion to the download list (because as a former macos user it could be useful), and also cleans up the messy abomination of the windows tab (orders them correctly ((hopefully)))

hopefully should work and clean it up a bit :D

### CODE REVIEW

**Comment by pumpkintheproot** [comment]
image
hm, im thinking my cleanup of the windows section did nothing, can see here its completely unordered
however, the products.json says otherwise
image

**Comment by pumpkintheproot** [comment]
@TheBobPony Broke website, unmerge please

**Comment by pumpkintheproot** [comment]
image

**Comment by TheBobPony** [comment]
Reverted, please test the website code before making changes!

**Comment by pumpkintheproot** [comment]
> Reverted, please test the website code before making changes!

kept getting errors when installing stuff with bundler or something and couldnt fix so ill try again 🙏

**Comment by pumpkintheproot** [comment]
@TheBobPony you sure you reverted? [dl page ](https://bobpony.com/downloads/) still broken on my end

**Comment by pumpkintheproot** [comment]
oh nevermind works now fsr lol

**Comment by pumpkintheproot** [comment]
getting a "Could not locate Gemfile or .bundle/ directory" when trying to start the page, any idea how to fix this? cant find any solution online

**Pull request merged**
